name: Seichi915ServerCore
version: 1.0.0
main: net.seichi915.seichi915servercore.Seichi915ServerCore
api-version: "1.13"
load: POSTWORLD
authors: [stouma915]
description: "seichi915Server コアプラグイン"
website: https://www.seichi915.net
depend:
  - CoreProtect
  - WorldGuard
  - Multiverse-Core
commands:
  fly:
    description: Toggle flying
    usage: /fly
    permission: seichi915servercore.command.fly
    permission-message: "§c権限が不足しています。"
permissions:
  seichi915servercore.*:
    description: Grant all permissions of seichi915ServerCore
    children:
      seichi915servercore.command.*: true
  seichi915servercore.command.*:
    description: Grant all command permissions of seichi915ServerCore
    children:
      seichi915servercore.command.fly: true
  seichi915servercore.command.fly:
    description: Permission to use /fly
    default: true
